name: ESJG
favicon: null
layout_spectrum: 0.4548501190729439
typography_spectrum: 0.9908827343024313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6057769665494561
  lightness: 0.37648698850534856
  saturation: 0.10291189840063453
  rhythmicContrast: 0.48566006147302687
purpose: []
